apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: node
      image: node:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
    - name: maven
      image: maven:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock